apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Nexus.v1alpha1.apps.m88i.io
  generateName: nexus-
  name: nexus
  namespace: nexus
spec:
  targetNamespaces:
  - nexus
