apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nexus-operator-hub
  namespace: nexus
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: nexus-operator-hub
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: nexus-operator.v0.1.0
