---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    app: apicurio-studio-auth
    template: apicurio-studio
  name: apicurio-studio-auth
spec:
  replicas: 1
  selector:
    app: apicurio-studio-auth
    deploymentconfig: apicurio-studio-auth
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apicurio-studio-auth
        deploymentconfig: apicurio-studio-auth
        template: apicurio-studio
    spec:
      containers:
      - env:
        - name: APICURIO_KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              key: keycloak-user
              name: apicurio-studio-auth
        - name: APICURIO_KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: keycloak-password
              name: apicurio-studio-auth
        - name: APICURIO_UI_URL
          value: https://apicurio-studio.apps.cluster.example.com
        image: auth:latest-release
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: apicurio-studio-auth
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1300Mi
          requests:
            cpu: 100m
            memory: 600Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/standalone/data
          name: keycloak-data
          readOnly: false
      dnsPolicy: ClusterFirst
      replicas: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - apicurio-studio-auth
      from:
        kind: ImageStreamTag
        name: auth:latest-release
    type: ImageChange
status: {}
