---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    app: apicurio-studio-ws
    template: apicurio-studio
  name: apicurio-studio-ws
spec:
  replicas: 1
  selector:
    app: apicurio-studio-ws
    deploymentconfig: apicurio-studio-ws
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apicurio-studio-ws
        deploymentconfig: apicurio-studio-ws
        template: apicurio-studio
    spec:
      containers:
      - env:
        - name: APICURIO_DB_DRIVER_NAME
          value: postgresql
        - name: APICURIO_DB_CONNECTION_URL
          value: jdbc:postgresql://postgresql:5432/apicuriodb
        - name: APICURIO_DB_TYPE
          value: postgresql9
        - name: APICURIO_DB_USER_NAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: postgresql
        - name: APICURIO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: postgresql
        - name: APICURIO_MIN_HEAP
          value: 512m
        - name: APICURIO_MAX_HEAP
          value: 1400m
        image: ws:latest-release
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: apicurio-studio-ws
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1800Mi
          requests:
            cpu: 100m
            memory: 900Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      replicas: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - apicurio-studio-ws
      from:
        kind: ImageStreamTag
        name: ws:latest-release
    type: ImageChange
  - type: ConfigChange
status: {}
