---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: apicurio-studio-api
    template: apicurio-studio
  name: apicurio-studio-api
spec:
  host: apicurio-studio-api.apps.cluster.example.com
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apicurio-studio-api
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: apicurio-studio-ws
    template: apicurio-studio
  name: apicurio-studio-ws
spec:
  host: apicurio-studio-ws.apps.cluster.example.com
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apicurio-studio-ws
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: apicurio-studio-ui
    template: apicurio-studio
  name: apicurio-studio-ui
spec:
  host: apicurio-studio.apps.cluster.example.com
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apicurio-studio-ui
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apicurio-studio-auth
  creationTimestamp: null
  labels:
    app: apicurio-studio-auth
    template: apicurio-studio
spec:
  host: apicurio-studio-auth.apps.cluster.example.com
  to:
    kind: Service
    name: apicurio-studio-auth
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
