---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql
    template: apicurio-studio
  name: postgresql
stringData:
  database-password: 2PMoRqg1cq72sJkb
  database-user: userIPW
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: apicurio-studio-auth
    template: apicurio-studio
  name: apicurio-studio-auth
stringData:
  keycloak-password: password
  keycloak-user: admin
