apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: orders
  labels:
    strimzi.io/cluster: my-cluster
  namespace: strimzi
spec:
  partitions: 40
  replicas: 3
  config:
    retention.ms: '604800000'
    segment.bytes: '1073741824'
