apiVersion: config.openshift.io/v1
kind: Console
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  authentication:
    logoutRedirect: https://keycloak-keycloak.apps.foo.sandbox1459.opentlc.com/auth/realms/OpenShift/protocol/openid-connect/logout?redirect_uri=https://console-openshift-console.apps.foo.sandbox1459.opentlc.com/
status: {}