apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
    app.kubernetes.io/instance: keycloak
  name: example-keycloak
  namespace: keycloak
spec:
  extensions:
  - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: false
  instances: 1
