---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    openshift.io/cluster-monitoring: "true"
  name: microcks
spec:
  finalizers:
  - kubernetes
