apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: openshift-client
spec:
  inputs:
    params:
      - name: ARGS
        description: The OpenShift CLI arguments to run
        default:
          - help
        type: array        
  steps:
  - args:
    - $(inputs.params.ARGS)
    command:
    - /usr/bin/oc
    image: quay.io/openshift/origin-cli:latest
    name: oc