apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build-base
    taskRef:
      name: s2i-quarkus
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "."
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image
  - name: build-cofeeshop-service
    taskRef:
      name: openshift-client  
    runAfter:
      - build-base
    params:
    - name: ARGS
      value:
       - start-build
       - coffeeshop-service
       - --wait
  - name: build-barista-http
    taskRef:
      name: openshift-client  
    runAfter:
      - build-base
    params:
    - name: ARGS
      value:
       - start-build
       - barista-http
       - --wait
  - name: barista-kafka-julie
    taskRef:
      name: openshift-client  
    runAfter:
      - build-base
    params:
    - name: ARGS
      value:
       - start-build
       - barista-kafka-julie
       - --wait
  - name: barista-kafka-tom
    taskRef:
      name: openshift-client  
    runAfter:
      - build-base
    params:
    - name: ARGS
      value:
       - start-build
       - barista-kafka-tom
       - --wait
  - name: deploy-cofeeshop-service
    taskRef:
      name: openshift-client
    runAfter:
      - build-cofeeshop-service
    params:
    - name: ARGS
      value:
       - rollout
       - latest
       - dc/coffeeshop-service
  - name: deploy-barista-http
    taskRef:
      name: openshift-client
    runAfter:
      - build-barista-http
    params:
    - name: ARGS
      value:
      - rollout
      - latest
      - dc/barista-http
  - name: deploy-barista-kafka-julie
    taskRef:
      name: openshift-client
    runAfter:
      - barista-kafka-julie
    params:
    - name: ARGS
      value:
      - rollout
      - latest
      - dc/barista-kafka-julie
  - name: deploy-barista-kafka-tom
    taskRef:
      name: openshift-client
    runAfter:
      - barista-kafka-tom
    params:
    - name: ARGS
      value:
      - rollout
      - latest
      - dc/barista-kafka-tom
