apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFmjCCBIKgAwIBAgISBNBqTjTbY5fZN6VzVBXRS3G4MA0GCSqGSIb3DQEBCwUA
    MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
    ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDAyMDExMTI1MThaFw0y
    MDA1MDExMTI1MThaMCoxKDAmBgNVBAMTH2FwaS5mb28uc2FuZGJveDE0NTkub3Bl
    bnRsYy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCz9aFtcL4
    ylUg4UIW4+4UbOww1mxl7FRr8bGEQkDH8AEoDM0V8pJvJXG6NOoJ91q12C3e/pT4
    ssP79Idvspprr+aF0oIOSl+RHsxjV/JCeyu9eXGJcsn8ZaSkjrpzQjY2E8UaLRFj
    KcdlEvyoxGO49n8ENIUlgzh1WYJFxhda1lzU8q4JNl5bDFriDoS6kEm2ViIf5da1
    kYN6VhxKiq9TpxyUh/N5Mo6v3xWK4GnatMLnfVy4jujutXvykvRMW+qt//vvq/Z9
    4r0F+HBc5QOe/H96o7bILryLWNZqCSWjaizqTmZrhrsIXMD2BK6+4gOGbx1iKJ/X
    Ckbrxf3jBfBvAgMBAAGjggKYMIIClDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYw
    FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFKjL
    CLM76IOmfBOeNjac/0xp2wdIMB8GA1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/z
    qOyhMG8GCCsGAQUFBwEBBGMwYTAuBggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50
    LXgzLmxldHNlbmNyeXB0Lm9yZzAvBggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50
    LXgzLmxldHNlbmNyeXB0Lm9yZy8wTgYDVR0RBEcwRYIiKi5hcHBzLmZvby5zYW5k
    Ym94MTQ1OS5vcGVudGxjLmNvbYIfYXBpLmZvby5zYW5kYm94MTQ1OS5vcGVudGxj
    LmNvbTBMBgNVHSAERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEBATAoMCYGCCsG
    AQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQQGCisGAQQB1nkC
    BAIEgfUEgfIA8AB1APCVpFnyANGCQBAtL5OIjq1L/h1H45nh0DSmsKiqjrJzAAAB
    cAC2Z48AAAQDAEYwRAIgba3H54VnjE5ZE/DOjbTVpTEVr9oA6NH74vsXtt/+SoYC
    IAKVHTkekkjwuU0DbwnOLExb8YyrfOVawJ2DcigsXqogAHcAB7dcG+V9aP/xsMYd
    IxXHuuZXfFeUt2ruvGE6GmnTohwAAAFwALZnugAABAMASDBGAiEAqqQoi5+Dt33g
    7frAFuOdJJu9O/2WlOHSsM74wa5w8w4CIQD2EcBsLiSsbz6HSdGVY/NtSlTOqZzq
    kyquo9KdSjjzNjANBgkqhkiG9w0BAQsFAAOCAQEAB42EnR66wzxtKz0ygC7NLfL6
    CuG5cTi4NmSJELaboVEY8Dup2egM91ToaJvYtGth/f5tg6mCtwI6QENFZEmQuDly
    3H57LoYgAzc6+t4BlLOYPr+j2gMr3mAz6TjecZ/o+BoBsdcYT3X12ULnExhOB8j+
    23Zza2hJw7DpoEf94jy6bBpGhSLGJa1WaeBCR2Xpp0ilTm6ahTh7NjYYrPhWbfhj
    AVrNUY4hD0qyd1+7fTGZcH3a3CYgwYFdbTdlxZesojed7gWXFWOdLhN+7KhrOSss
    n2/IxB4DvUtlOtKZcHVwURKb+TtEk2CteJZ839QIAClyOQX5MUfe7VCA5bT0dw==
    -----END CERTIFICATE-----

    -----BEGIN CERTIFICATE-----
    MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
    MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
    DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
    SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
    GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
    q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
    SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
    Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
    a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
    /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
    AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
    CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
    bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
    c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
    VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
    ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
    MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
    Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
    AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
    uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
    wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
    X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
    PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
    KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
    -----END CERTIFICATE-----

kind: ConfigMap
metadata:
  name: ca-config-map
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false  
    argocd.argoproj.io/compare-options: IgnoreExtraneous
