namespace: apicurito

resources:
- namespace.yaml
- operatorgroup.yaml
- create-apicurito.yaml
- subscription.yaml

# patchesJson6902:
# - target:
#     group: route.openshift.io
#     version: v1
#     kind: Route
#     name: apicurito-service
#   path: tls-route.yaml
