---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: apicurito
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: apicurito
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: apicuritooperator.v0.1.0
